In [1]:
import os 
import pandas as pd 
import numpy as np

## He

In [23]:
df  = pd.read_csv("./_[DATA]He_293K_20250407ver.csv").iloc[: , 1:]
df.columns=["name"] + ['He_293_0.01',
 'He_293_0.05',
 'He_293_0.1',
 'He_293_0.2',
 'He_293_0.35',
 'He_293_0.5',
 'He_293_1',
 'He_293_5',
 'He_293_15']

He = pd.read_csv("./He_results.csv")
# He.columns, df.columns
print(len(He), len(df))
merged = pd.merge(df, He,left_on="name", right_on="name", how = 'right')
merged[['name',
       'He_273_0.01', 'He_273_0.05', 'He_273_0.1', 'He_273_0.5', 'He_273_1',
       'He_273_5', 'He_273_15',
         'He_293_0.01', 'He_293_0.05', 'He_293_0.1', 'He_293_0.2',
       'He_293_0.35', 'He_293_0.5', 'He_293_1', 'He_293_5', 'He_293_15',
         'He_313_0.01', 'He_313_0.05', 'He_313_0.1',
       'He_313_0.5', 'He_313_1', 'He_313_5', 'He_313_15']]
# df
merged.to_csv("./He_results_V2(293Kadded).csv", index=False)

10788 12022

In [99]:
times = pd.read_csv("./mof_times_wide_V1.csv")
He_time = pd.read_csv("./_[DATA]He_CPUTIME.csv").iloc[:, 1:]
He_time.columns , times.columns

[ "He_" + "293_" +  i.replace("bar time (s)","") for i in ['0.01bar time (s)', '0.05bar time (s)', '0.1bar time (s)',
        '0.2bar time (s)', '0.35bar time (s)', '0.5bar time (s)',
        '15bar time (s)', '1bar time (s)', '5bar time (s)']]
He_time.columns = ["MOF" ] + ['He_293_0.01',
 'He_293_0.05',
 'He_293_0.1',
 'He_293_0.2',
 'He_293_0.35',
 'He_293_0.5',
 'He_293_15',
 'He_293_1',
 'He_293_5']
times.columns, He_time.columns
merged_time = pd.merge(times, He_time,left_on="Unnamed: 0", right_on="MOF", how = 'outer')
# merged_time.columns = ['MOF', 'Ar_273_0.1', 'Ar_273_0.01', 'Ar_273_0.5', 'Ar_273_0.05',
#        'Ar_273_1', 'Ar_273_5', 'Ar_273_15', 'Ar_313_0.1', 'Ar_313_0.01',
#        'Ar_313_0.5', 'Ar_313_0.05', 'Ar_313_1', 'Ar_313_5', 'Ar_313_15',
#        'H2_293_0.01', 'H2_293_5', 'He_273_0.1', 'He_273_0.01', 'He_273_0.05',
#        'He_273_0.5', 'He_273_1', 'He_273_5', 'He_273_15','He_293_0.01', 'He_293_0.05', 'He_293_0.1', 'He_293_0.2',
#        'He_293_0.35', 'He_293_0.5', 'He_293_15', 'He_293_1', 'He_293_5', 'He_313_0.1',
#        'He_313_0.01', 'He_313_0.05', 'He_313_0.5', 'He_313_1', 'He_313_5',
#        'He_313_15', 'N2_293_0.01', 'N2_293_5', 'O2_293_0.01', 'O2_293_5',
#        'Unnamed: 0']
# merged_time
# merged_time["MOF"]
# merged_time.drop(columns=["Unnamed: 0"], inplace=True)
merged_time
merged_time.to_csv("./mof_times_wide_V2(293Kadded).csv", index=False)

In [116]:
for i , j in zip(list(merged_time["Unnamed: 0"].to_dict().values()), list(merged_time["MOF"].to_dict().values())):
    # print(type(i)   )
    # print(i)
    if type(i) == float:
        print(j)
        # merged_time["Unnamed: 0"].replace(i, j, inplace=True)

## Ar

In [71]:
T293 =  pd.read_csv("./argon_results_293K.csv").iloc[:, 1:]

T293
Ar = pd.read_csv("./Ar_results.csv")
# len(Ar) , len(T293)

pd.merge(T293, Ar,left_on="MOF", right_on="name", how = 'left').to_csv("./Ar_results_V2(293Kadded).csv", index=False)
# He = pd.read_csv("./He_results.csv")
# # He.columns, df.columns
# print(len(He), len(df))
# merged = pd.merge(df, He,left_on="name", right_on="name", how = 'right')
# merged[['name',
#        'He_273_0.01', 'He_273_0.05', 'He_273_0.1', 'He_273_0.5', 'He_273_1',
#        'He_273_5', 'He_273_15',
#          'He_293_0.01', 'He_293_0.05', 'He_293_0.1', 'He_293_0.2',
#        'He_293_0.35', 'He_293_0.5', 'He_293_1', 'He_293_5', 'He_293_15',
#          'He_313_0.01', 'He_313_0.05', 'He_313_0.1',
#        'He_313_0.5', 'He_313_1', 'He_313_5', 'He_313_15']]
# # df
# merged.to_csv("./He_results_V2(293Kadded).csv", index=False)

In [67]:
T293

,MOF,Ar_293_0.01,Ar_293_0.05,Ar_293_0.1,Ar_293_0.5,Ar_293_15,Ar_293_1,Ar_293_5
0,00958972.2016.1250260_1436516_clean,0.001022,0.005061,0.010323,0.051217,1.168075,0.101349,0.470484
1,00958972.2016.1250260_1436519_clean,0.002505,0.013304,0.027102,0.130413,1.793717,0.247224,0.898819
2,00958972.2016.1253069_1472494_clean,0.000458,0.002121,0.004455,0.021950,0.507998,0.043608,0.198091
3,1499489-acs.cgd.6b01265_1499490_clean,0.007367,0.037364,0.074553,0.360855,5.602302,0.685041,2.784855
4,ABAVIJ_clean,0.011057,0.054359,0.105149,0.425300,1.526816,0.676755,1.282917
...,...,...,...,...,...,...,...,...
12017,ncomms13008_ncomms13008-s4_clean,0.001798,0.008825,0.017569,0.084687,1.059399,0.161286,0.579197
12018,ncomms7350-s2_clean,0.001950,0.009238,0.018578,0.091365,1.685482,0.176758,0.750969
12019,om701262m-file004_clean,0.003172,0.015846,0.032223,0.157547,3.146789,0.308073,1.373220
12020,sciadv.1600621_S1_Crystal_Structures_clean,0.002609,0.013648,0.026808,0.131717,2.590283,0.261898,1.110389
12021,science.1056698_manual,0.004577,0.023316,0.046893,0.229281,4.724761,0.448286,1.951940

In [93]:
times

,Unnamed: 0,Ar_273_0.1,Ar_273_0.01,Ar_273_0.5,Ar_273_0.05,Ar_273_1,Ar_273_5,Ar_273_15,Ar_313_0.1,Ar_313_0.01,...,He_313_0.01,He_313_0.05,He_313_0.5,He_313_1,He_313_5,He_313_15,N2_293_0.01,N2_293_5,O2_293_0.01,O2_293_5
0,1499489-acs.cgd.6b01265_1499490_clean,508.0,229.0,516.0,385.0,772.0,3013.0,4222.0,381.0,172.0,...,146.0,168.0,171.0,197.0,299.0,318.0,836.0,7954.0,723.0,7725.0
1,ABAYIO_clean,861.0,463.0,1352.0,670.0,2460.0,9195.0,18598.0,688.0,331.0,...,193.0,237.0,537.0,525.0,580.0,899.0,1858.0,24371.0,NaN,NaN
2,ABAYOU_clean,859.0,488.0,1383.0,704.0,2643.0,9851.0,21457.0,687.0,332.0,...,269.0,308.0,665.0,520.0,591.0,907.0,1924.0,25613.0,NaN,NaN
3,ABEFUL_clean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.0,59.0,62.0,62.0,116.0,168.0,NaN,NaN,NaN,NaN
4,ABESUX_clean,175.0,66.0,193.0,121.0,213.0,889.0,1995.0,118.0,51.0,...,47.0,52.0,87.0,95.0,152.0,159.0,376.0,3005.0,309.0,2710.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11132,ncomms7350-s2_clean,362.0,143.0,468.0,253.0,472.0,1038.0,2195.0,248.0,124.0,...,120.0,123.0,182.0,211.0,387.0,435.0,840.0,4175.0,762.0,3858.0
11133,ncomms11831_ncomms11831-s2_clean,532.0,366.0,1031.0,442.0,1356.0,1878.0,2179.0,430.0,221.0,...,131.0,138.0,177.0,178.0,334.0,429.0,NaN,NaN,1392.0,7421.0
11134,ncomms11831_ncomms11831-s3_clean,535.0,342.0,907.0,439.0,1335.0,2200.0,2515.0,437.0,203.0,...,138.0,145.0,195.0,187.0,361.0,455.0,1465.0,7923.0,1387.0,8476.0
11135,om701262m-file004_clean,396.0,145.0,425.0,269.0,509.0,1849.0,4151.0,270.0,114.0,...,108.0,118.0,187.0,202.0,320.0,320.0,781.0,6574.0,NaN,NaN
11136,science.1056698_manual,436.0,187.0,471.0,338.0,531.0,2011.0,4914.0,335.0,147.0,...,108.0,123.0,247.0,297.0,382.0,404.0,825.0,7281.0,773.0,6817.0

In [44]:
times

,Unnamed: 0,Ar_273_0.1,Ar_273_0.01,Ar_273_0.5,Ar_273_0.05,Ar_273_1,Ar_273_5,Ar_273_15,Ar_313_0.1,Ar_313_0.01,...,He_313_0.01,He_313_0.05,He_313_0.5,He_313_1,He_313_5,He_313_15,N2_293_0.01,N2_293_5,O2_293_0.01,O2_293_5
0,1499489-acs.cgd.6b01265_1499490_clean,508.0,229.0,516.0,385.0,772.0,3013.0,4222.0,381.0,172.0,...,146.0,168.0,171.0,197.0,299.0,318.0,836.0,7954.0,723.0,7725.0
1,ABAYIO_clean,861.0,463.0,1352.0,670.0,2460.0,9195.0,18598.0,688.0,331.0,...,193.0,237.0,537.0,525.0,580.0,899.0,1858.0,24371.0,NaN,NaN
2,ABAYOU_clean,859.0,488.0,1383.0,704.0,2643.0,9851.0,21457.0,687.0,332.0,...,269.0,308.0,665.0,520.0,591.0,907.0,1924.0,25613.0,NaN,NaN
3,ABEFUL_clean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.0,59.0,62.0,62.0,116.0,168.0,NaN,NaN,NaN,NaN
4,ABESUX_clean,175.0,66.0,193.0,121.0,213.0,889.0,1995.0,118.0,51.0,...,47.0,52.0,87.0,95.0,152.0,159.0,376.0,3005.0,309.0,2710.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11132,ncomms7350-s2_clean,362.0,143.0,468.0,253.0,472.0,1038.0,2195.0,248.0,124.0,...,120.0,123.0,182.0,211.0,387.0,435.0,840.0,4175.0,762.0,3858.0
11133,ncomms11831_ncomms11831-s2_clean,532.0,366.0,1031.0,442.0,1356.0,1878.0,2179.0,430.0,221.0,...,131.0,138.0,177.0,178.0,334.0,429.0,NaN,NaN,1392.0,7421.0
11134,ncomms11831_ncomms11831-s3_clean,535.0,342.0,907.0,439.0,1335.0,2200.0,2515.0,437.0,203.0,...,138.0,145.0,195.0,187.0,361.0,455.0,1465.0,7923.0,1387.0,8476.0
11135,om701262m-file004_clean,396.0,145.0,425.0,269.0,509.0,1849.0,4151.0,270.0,114.0,...,108.0,118.0,187.0,202.0,320.0,320.0,781.0,6574.0,NaN,NaN
11136,science.1056698_manual,436.0,187.0,471.0,338.0,531.0,2011.0,4914.0,335.0,147.0,...,108.0,123.0,247.0,297.0,382.0,404.0,825.0,7281.0,773.0,6817.0

In [87]:
import pandas as pd

timeAr = pd.read_csv("./mof_times_wide.csv")
time = pd.read_csv("./mof_times_wide_V2(293Kadded).csv")

merged = pd.merge(
    time, timeAr,
    left_on="MOF", right_on="Unnamed: 0",
    how="outer"
)

# 대표 키 열: MOF, Unnamed: 0 중 NaN이 아닌 값 선택
merged["MOF_key"] = merged["MOF"].combine_first(merged["Unnamed: 0"])

# # 열 순서 재정렬: MOF_key 맨 앞에 두고 나머지
# cols = ["MOF_key"] + [c for c in merged.columns if c not in ["MOF_key", "MOF", "Unnamed: 0"]]
# merged = merged[cols]

# # 저장
# merged.to_csv("mof_times_merged.csv", index=False, encoding="utf-8-sig")

# merged

In [92]:
merged["MOF"]
# merged["Unnamed: 0"]

0          00958972.2016.1250260_1436516_clean
1          00958972.2016.1250260_1436519_clean
2          00958972.2016.1253069_1472494_clean
3        1499489-acs.cgd.6b01265_1499490_clean
4                                 ABAVIJ_clean
                         ...
12650                                      NaN
12651                                      NaN
12652                                      NaN
12653                                      NaN
12654                                      NaN
Name: MOF, Length: 12655, dtype: object